Support for sparse data structures in tidymodels
tidyverse/tidyverse.org pull request #481
Opened 2020-11-16 19:05 UTC by juliasilge

This blog post should be published **after** the main tune blog post announcement by at least a day or so, and is flexible about when exactly it goes out.

2020-11-16 19:06 UTC, juliasilge commented
I can't assign reviewers in this repo but @topepo take a look! 👀

2020-11-16 19:40 UTC, topepo requested changes

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +The new release of [tune](linktopost) is chock full of improvements and new features. When combined with the latest releases of [hardhat](http://hardhat.tidymodels.org/) and [parsnip](https://parsnip
"limited support" maybe? I'm worried about people starting with a sparse matrix

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +
I'd briefly mention how sparse matrices work under the hood and maybe do an `obj_size()` calculation with it and its data frame version.

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +The `dgCMatrix` composition is from the [Matrix](https://cran.r-project.org/package=Matrix) package, and is the most standard class for sparse numeric matrices in modeling in R. You can also specify
Somewhere, maybe here, we should differentiate what can _can_ do now versus what you _still can't_ do. IIRC you can start with a sparse matrix only if you use `fit_xy()` with a `parsnip` model. For example: 

```r
library(tidymodels)
library(Matrix)
library(hardhat)

data("hpc_data", package = "modeldata")

# ------------------------------------------------------------------------------

# Can do this: 
new_x <- Matrix::sparse.model.matrix(class ~ protocol + day, data = hpc_data)

cls_spec <- 
  multinom_reg(penalty = .1, mixture = 0.5) %>% 
  set_engine("glmnet", nlambda = 5)

# input is sparse
fit_xy(cls_spec, x = new_x, y = hpc_data$class)

# ------------------------------------------------------------------------------
# can do this:

sparse_bp <- default_recipe_blueprint(composition = "dgCMatrix")

rec <- 
  recipe(class ~ protocol + day, data = hpc_data) %>% 
  step_dummy(all_predictors())

wflow <- 
  workflow() %>% 
  add_recipe(rec, blueprint = sparse_bp) %>% 
  add_model(cls_spec)

#input still has to be a data frame but data gets converted and passed to model as sparse
wflow %>% fit(data = hpc_data)

# can't do anything else really
```

Somewhere we should say this.

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +
Start a new subsection on modeling

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +
list the three models that support a "sparse handoff"

2020-11-16 19:40 UTC, topepo commented on content/blog/tidymodels-sparse-support/index.Rmd
> +The new release of [tune](linktopost) is chock full of improvements and new features. When combined with the latest releases of [hardhat](http://hardhat.tidymodels.org/) and [parsnip](https://parsnip
Mention that this is the second of three articles related to tune 0.1.2 and use link to previous (which should be `/blog/2020/11/tune-0-1-2/`)

2020-11-16 19:41 UTC, topepo commented
One other question... should we drop all three posts the same day? @batpigandme does this matter?

2020-11-16 22:53 UTC, juliasilge commented
Another option would be to post the main tune announcement one day and the followup posts both the day after? I don't hold any strong opinions on this.

2020-11-17 13:37 UTC, batpigandme commented
> One other question... should we drop all three posts the same day? @batpigandme does this matter?

While it doesn't technically matter, I think it can sort of "dilute" the impact—I don't think there'd be any harm in spacing them out across days (though feel free to override, of course).

2020-11-17 14:52 UTC, topepo commented
`tune` was accepted this morning. I'll post the first article on Monday (binaries might be built by then). Let's post this article next Wednesday and I'll post the third on Friday.

2020-11-25 16:17 UTC, merged