add stacks 0.1.0 blog post
tidyverse/tidyverse.org pull request #484
Opened 2020-11-17 17:01 UTC by simonpcouch

Now that tune 0.1.2 is on CRAN, we should be good to go to submit the first version of stacks to CRAN. Planning on submitting sometime tomorrow, and will keep this thread up to date!

Also, will need to update the `date` YAML.

cc @topepo

2020-11-23 15:05 UTC, topepo requested changes

2020-11-23 15:05 UTC, topepo commented on content/blog/stacks-0-1-0/index.Rmd
> +date: 2020-11-17
Go ahead and change the date (anything this week is fine) and re-knit

EDIT: Actually, wait until the binaries are built.

2020-11-23 15:05 UTC, topepo commented on content/blog/stacks-0-1-0/index.Rmd
> +  - tidymodels
Can you add `stacks` as a tag?

2020-11-23 15:33 UTC, simonpcouch commented
Accepted this morning!

Just made those edits, bumped date until tomorrow for now.

2020-11-27 20:59 UTC, simonpcouch commented
Binaries built this mornin! Bumped the date to this Monday the 30th.

2020-11-30 13:19 UTC, merged