infer 1.0.0 blog post
tidyverse/tidyverse.org pull request #517
Opened 2021-06-25 19:02 UTC by simonpcouch

A blog post for the first major release of [tidymodels/infer](https://github.com/tidymodels/infer)! This is the first tidyverse.org post on the package, so the first half introduces the big ideas of the package and the second gives an overview of the new functionality in v1.0.0.

We plan to submit to CRAN the week of July 12th—this post is tentatively dated for the 19th.

cc @mine-cetinkaya-rundel

2021-08-10 04:06 UTC, mine-cetinkaya-rundel requested changes
Looks great! Some suggestions on phrasing as well as consistency of language particularly regarding bootstrapping not coming after hypothesize for confidence intervals.

Date should also be changed to a date after CRAN release, that can happen when CRAN release goes through.

2021-08-10 04:06 UTC, mine-cetinkaya-rundel commented on content/blog/infer-1-0-0/index.Rmd
> +    level = .95,
```suggestion
    level = 0.95,
```

2021-08-10 12:23 UTC, simonpcouch commented
The draft is much clearer with your edits--thank you🦋

2021-08-10 13:25 UTC, mine-cetinkaya-rundel approved these changes
Looks great with the changes in place!

Approving the PR now but one pending item before publishing will be to adjust the blog post date based on CRAN release date + preferences (if any) from the tidyverse team.

2021-08-11 16:41 UTC, simonpcouch commented
Submitted to CRAN! Will update the post's release date upon acceptance.

2021-08-13 18:27 UTC, simonpcouch commented
v1.0.0 was accepted to CRAN!🎉 Will change the date of the post to this Monday the 16th.

2021-08-17 12:48 UTC, hadley approved these changes

2021-08-17 12:48 UTC, hadley commented on content/blog/infer-1-0-0/index.Rmd
> +We're super excited announce the release of [infer](https://infer.tidymodels.org/) 1.0.0! infer is a package for statistical inference that implements an expressive statistical grammar that adheres t
Is it worth a sentence somewhere that this is specifically designed for teaching?

2021-08-17 12:48 UTC, hadley commented on content/blog/infer-1-0-0/index.Rmd
> +date: 2021-08-16
Needs an update

2021-08-17 12:48 UTC, hadley commented on content/blog/infer-1-0-0/index.Rmd
> +```
This (and below) needs to be indented to correctly line up the bullets.

2021-08-17 18:56 UTC, merged